directories:
  output: SmartLab-Release
  buildResources: build
appId: com.smartlab.assist
productName: SmartLab_Assist
extraResources:
  - from: activity_monitor.exe
    to: activity_monitor.exe
  - from: ../backend
    to: backend
    filter:
      - '**/*'
      - '!public/**/*'
      - '!.env'
  - from: ../backend/.env
    to: backend/.env
files:
  - filter:
      - main.js
      - preload.js
      - renderer/**/*
      - package.json
win:
  requestedExecutionLevel: asInvoker
  target:
    - target: nsis
      arch:
        - x64
    - target: zip
      arch:
        - x64
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: null
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: SmartLab Assist
electronVersion: 31.7.7
